openapi: "3.1.0"
info:
  title: "backend_transport API"
  description: "backend_transport API"
  version: "1.0.0"
servers:
  - url: "https://127.0.0.1:8000"
paths:
  /api/orders:
    get:
      summary: "GET api/orders"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: "POST api/orders"
      responses:
        "201":
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /api/orders/{order_number}:
    get:
      summary: "GET api/orders/{order_number}"
      parameters:
        - name: order_number
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          example: 2
        order_number:
          type: string
          example: "ORD124"
        customer_name:
          type: string
          example: "Alice Smith"
        date:
          type: string
          format: date
          example: "2025-09-15"
        waypoints:
          type: array
          items:
            $ref: '#/components/schemas/Waypoint'
    Waypoint:
      type: object
      properties:
        id:
          type: integer
          example: 4
        location:
          type: string
          example: "San Francisco"
        type:
          type: string
          example: "Delivery"
